const motionBoundaryFix=document.createElement('style');motionBoundaryFix.textContent=`
.plane-track{overflow:hidden;contain:paint;isolation:isolate}
.track-signal{left:-36%;width:36%;will-change:transform}
@keyframes signal-run{from{transform:translateX(0)}to{transform:translateX(378%)}}
`;document.head.appendChild(motionBoundaryFix);
const menu=document.querySelector('.menu-btn');const links=document.querySelector('.nav-links');if(menu){menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));links.classList.toggle('open',!open);});}
const scenarios={stable:{decision:'Automate + standardize',state:'Synchronized for scale',explain:'Stable rules, visible exceptions, named ownership, and instrumented control evidence support a durable automation standard.',cls:'',work:['Clear need','Stable steps','Rules-led decision','Visible outcome'],assure:['Named owner','Bound authority','Logged evidence','Active monitoring']},exception:{decision:'Redesign, then assist',state:'Work plane outruns process truth',explain:'Cross-system exceptions and handoff ambiguity should be simplified before automation amplifies the maze.',cls:'is-lagging',work:['Mixed demand','Variable steps','Handoff conflict','Rework risk'],assure:['Shared owner','Authority gap','Partial evidence','Reactive monitoring']},human:{decision:'Assist + retain authority',state:'Human judgment remains a control',explain:'Use automation to prepare, retrieve, route, or recommend while keeping the member-context decision visibly human.',cls:'is-human',work:['Member need','AI-assisted prep','Human decision','Personalized outcome'],assure:['Named owner','Human authority','Decision record','Quality review']},evidence:{decision:'Hold + instrument',state:'Assurance is not ready',explain:'A process may be technically automatable and still be unfit for scale when control evidence, monitoring, or fallback is weak.',cls:'is-hold',work:['Clear need','Stable steps','Bounded action','Expected outcome'],assure:['Owner unclear','Authority untested','Evidence missing','Monitoring absent']}};
function applyScenario(key,prefix='model'){const s=scenarios[key];const shell=document.getElementById(prefix+'-twin');if(!shell)return;shell.className='twin-shell '+s.cls;const d=document.getElementById(prefix+'-decision'),st=document.getElementById(prefix+'-state'),ex=document.getElementById(prefix+'-explain');if(d)d.textContent=s.decision;if(st)st.textContent=s.state;if(ex)ex.textContent=s.explain;if(prefix==='model'){s.work.forEach((v,i)=>document.getElementById('work-'+(i+1)).textContent=v);s.assure.forEach((v,i)=>document.getElementById('assure-'+(i+1)).textContent=v);}}
document.querySelectorAll('[data-scenario]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-scenario]').forEach(b=>b.setAttribute('aria-selected','false'));btn.setAttribute('aria-selected','true');applyScenario(btn.dataset.scenario,'model');applyScenario(btn.dataset.scenario,'hero');}));
